name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore BlazorApp1.csproj

      - name: Build and Publish Blazor WebAssembly
        run: dotnet publish BlazorApp1.csproj -c Release

      - name: Find Published Output
        run: |
          echo "Finding published output..."
          PUBLISH_DIR=$(find . -type d -name "wwwroot" | grep "bin/Release/net8.0")
          echo "Publish directory: $PUBLISH_DIR"
          echo "PUBLISH_DIR=$PUBLISH_DIR" >> $GITHUB_ENV

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_POND_0650D6F1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "${{ env.PUBLISH_DIR }}" # Corrected publish output directory
          api_location: "" # No API functions
          output_location: "wwwroot"
          app_build_command: "dotnet publish BlazorApp1.csproj -c Release" # Force Oryx to build properly

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_POND_0650D6F1E }}
          action: "close"
